### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by carolinavc99** [DemocraciaEnRed/votacion-autoridades#1]
Hello @guillecro I see you are the one who has updated this code the last time.
There are no instructions on how to install Votación de Autoridades and I was wondering if there was any way of providing them as I would like to test it out.
Thank you.

**Comment by guillecro** [comment]
Hi!
Thanks for your interest in this repository.
Sadly, this project was outsourced and our provider didn't include documentation.
We were working on something, but that will be available in a month or two.

On it's core it's been done with Laravel, which is a framework quite well known and usually the installation is pretty the same in each Laravel project. So any php developer could understand on how to install it.

Do you have one?

**Comment by carolinavc99** [comment]
Thank you for answering so fast!
This is for my master's thesis where I'm comparing a few voting software solutions. I'm familiar with php although unfortunately I'm not very familiar with deploying projects. I can do it, just perhaps not without any instruction.

The only thing I really needed here was to explore it as a normal user would, and take notes. For example "the option to extract data to a .csv file is available", "You can customize the list of trustees", "You can set voter weight by individual voter" - honestly nothing technical even. In the off-chance that there is some sort of demo or maybe a docker image I could use, that would be great. But that's just a long shot! I'm asking just in case - and I know there probably isn't anything of the sort available.

Thank you for the tip about Laravel, I'm also familiar with it and will proceed with that. I appreciate the help.

**Comment by guillecro** [comment]
I am very busy until the 20th of this month.. But I would love to help you if I can, later that date I can try to check the software and detail you all your questions. Drop me an email if you prefer.

Maybe it is for your interest, but I also make other developments, like: this one which is for a open budget for the municipality of San lorenzo: https://pp.sanlorenzo.gob.ar (the general one) and https://ppjoven.sanlorenzo.gob.ar which is the edition for young citizens.

**Comment by carolinavc99** [comment]
Hello, I understand this is anticlimatic, but I've realized that DemocraciaOS is not exactly the type of voting software that I was looking for in my analysis (SaaS voting software, a service like spotify for example), and that is my mistake. Apologies 😅

Thank you for the links, while they do not apply to my thesis' theme, it's refreshing to see these types of youth-engaging voting activities. Portugal needs one of these for sure!

Nevertheless, thank you SO much for your help and readiness. Best of luck with your work and developments.
